# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "759aead17dfbcb721121009dacc43ce2"
name = "Noteyâ€‘ Product Notes for Staff"
handle = "product-notes-for-staff"
application_url = "https://product-notes-for-staff.up.railway.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "fulfillment_orders/hold_released" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/webhooks"

[access.admin]
direct_api_mode = "offline"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_fulfillments,write_fulfillments"

[auth]
redirect_urls = [
  "https://product-notes-for-staff.up.railway.app/auth/callback",
  "https://product-notes-for-staff.up.railway.app/auth/shopify/callback"
]

[app_proxy]
url = "https://product-notes-for-staff.up.railway.app/"
subpath = "product-notes"
prefix = "apps"

[pos]
embedded = false
