api_version = "2025-07"

[[extensions]]

uid = "34f2e8d1-f8e9-8f31-13c7-1f9886dc0e53127f2877"

type = "ui_extension"
name = "Order Fulfillment Notes"
handle = "order-fulfillment-notes"

[[extensions.targeting]]
target = "admin.order-details.block.render"
module = "./src/OrderDetailsBlock.tsx"

[extensions.network_access]
allowed_domains = ["shopify-internal-notes-app-production.up.railway.app"]