api_version = "2025-01"

[[extensions]]

uid = "cf0823c6-3e0a-99df-15a8-46670618eca63453b1fb"

type = "ui_extension"
name = "Product Notes"
handle = "product-notes"

[[extensions.targeting]]
target = "admin.product-details.block.render"
module = "./src/ProductNotesBlock.tsx"

[extensions.network_access]
allowed_domains = ["product-notes-for-staff.up.railway.app"]

# Enable direct API mode for authenticated requests
[extensions.capabilities]
api_access = true